#!/bin/bash

## Assumes you have a "gtweb" entry in ~/.ssh/config, e.g.:
#
# Host gtweb
#   User unhammer
#   HostName gtweb.uit.no


set -eu

svn () {
    cd "$(dirname "$0")"/..

    if [[ ! -f Makefile ]]; then
        echo 'No Makefile found – please compile first!' >&2
        exit 1
    elif [[ "$(grep ^prefix Makefile)" != "prefix = /usr/local" ]]; then
        echo "Please run autogen.sh again without any --prefix" >&2
        exit 1
    fi

    echo "Compiling and running sanity check …"
    make -j test

    DESTDIR=for_gtweb_jorgal make install

    echo
    echo "Transferring files to gtweb …"
    rsync -av for_gtweb_jorgal/ gtweb:for_gtweb_jorgal/

    echo
    echo "On gtweb, copying to /usr and restarting apy …"
    set -x
    ssh -t gtweb '
sudo rsync -a for_gtweb_jorgal/usr/local/share/apertium/apertium-sme-nob/ /usr/share/apertium/apertium-sme-nob/ &&
sudo systemctl restart apy
'
}

package () {
    set -x
    ssh -t gtweb '
sudo dnf clean packages             &&
sudo dnf update                     &&
sudo dnf reinstall apertium-sme-nob &&
sudo systemctl restart apy
'
}

fail () {
    cat >&2 <<EOF
Usage:

 $0 svn        --  compiles this package, uploads to gtweb and installs it to /usr
 $0 package    --  reinstalls the nightly package on gtweb

Assumes you have a Host gtweb in ~/.ssh/config
EOF
    exit 1
}

if [[ $# -ne 1 ]]; then
    fail
fi
case $1 in
    svn) shift; svn "$@";;
    package) package;;
    *) fail;;
esac
