#!/bin/bash

set -e -u

cd "$(dirname "$0")"


for tag in NOTART HASART; do
    grep "@${tag}" ./results \
        | sed "s/@${tag}//g"  \
        | awk '{print(tolower($0))}'  \
        | sort \
        | uniq -c  \
        | sed $'s/^ *//;s/ /\t/' > "./${tag}" &
done
wait

join -j2 -a1 -a2 -o'0,1.1,2.1' -e'0' -t$'\t' \
     <(sort -k2b,2 -t$'\t' ./HASART) \
     <(sort -k2b,2 -t$'\t' ./NOTART) \
     > ./joined

# Articles are not evenly distributed! Ratio about 5 in this corpus:
tothas=$(awk '{s+=$1}END{print s}' ./HASART)
totnot=$(awk '{s+=$1}END{print s}' ./NOTART)
ratio=$(calc -p "round(${totnot}/${tothas},5)")

# Keep the ones where NOTART count is more than ratio*HASART, skipping hapaxes:
awk -F'\t' -vr="${ratio}" '$3 > r*$2 && $3 > 1 { print $1 }' ./joined > neverdetind

# Keep the ones where ratio*HASART count is more than than NOTART:
awk -F'\t' -vr="${ratio}" 'r*$2 > $3 { print $1 }' ./joined > maydetind

awk 'BEGIN {
       while(getline<"maydetind") d[$0]++
     }
     {
       gsub(/<par n="maydetind__n"\/>/, "")
     }
     /<s n="n"/ && !/par n="unc__n"/ {
       r = gensub(/.*<r>(.*)<s n="n".*/, "\\1", "1")
       if(r in d) sub("</e>", "<par n=\"maydetind__n\"/></e>")
     }
     {
       print
     }' \
         ../../apertium-sme-nob.sme-nob.dix
